baseurl: ""
url: "https://www.lec-tu-ra.com"

title: Lectura
theme: minima

defaults:
  - scope:
      path: ""
    values:
      layout: page
  - scope:
      path: "vision/index.md"
    values:
      permalink: /vision/

header_pages:
  - produits/index.md
  - projets/index.md
  - methode/index.md
  - vision/index.md
